/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veloziped.ws1516.main;

import java.util.ResourceBundle;
import veloziped.ws1516.util.Utils;

/**
 *
 * @author Mihai Sava
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelProductionPlanning = new javax.swing.JPanel();
        jLabelFairyCyclePF = new javax.swing.JLabel();
        jLabelLadiesCyclePF = new javax.swing.JLabel();
        jLabelMenCyclePF = new javax.swing.JLabel();
        jLabelPeriodNPF = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImportFile = new javax.swing.JMenuItem();
        jMenuItemExportFile = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuLanguage = new javax.swing.JMenu();
        jCheckBoxMenuItemDeutsch = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEnglish = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("veloziped/ws1516/i18n/i18n"); // NOI18N
        setTitle(bundle.getString("pps")); // NOI18N

        jPanelProductionPlanning.setAutoscrolls(true);

        jLabelFairyCyclePF.setText(bundle.getString("fairyCycle")); // NOI18N

        jLabelLadiesCyclePF.setText(bundle.getString("LadiesCycle")); // NOI18N

        jLabelMenCyclePF.setText(bundle.getString("MenCycle")); // NOI18N

        jLabelPeriodNPF.setText(bundle.getString("PeriondN")); // NOI18N

        javax.swing.GroupLayout jPanelProductionPlanningLayout = new javax.swing.GroupLayout(jPanelProductionPlanning);
        jPanelProductionPlanning.setLayout(jPanelProductionPlanningLayout);
        jPanelProductionPlanningLayout.setHorizontalGroup(
            jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMenCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLadiesCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFairyCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabelPeriodNPF, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanelProductionPlanningLayout.setVerticalGroup(
            jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelPeriodNPF, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabelFairyCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLadiesCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMenCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("tabProductionForecast"), jPanelProductionPlanning); // NOI18N

        jMenuFile.setText(bundle.getString("File")); // NOI18N

        jMenuItemImportFile.setText(bundle.getString("ImportFile")); // NOI18N
        jMenuFile.add(jMenuItemImportFile);

        jMenuItemExportFile.setText(bundle.getString("ExportFile")); // NOI18N
        jMenuFile.add(jMenuItemExportFile);

        jMenuBar1.add(jMenuFile);

        jMenuSettings.setText(bundle.getString("Settings")); // NOI18N

        jMenuLanguage.setText(bundle.getString("Language")); // NOI18N

        jCheckBoxMenuItemDeutsch.setText(bundle.getString("Deutsch")); // NOI18N
        jCheckBoxMenuItemDeutsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDeutschActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemDeutsch);

        jCheckBoxMenuItemEnglish.setSelected(true);
        jCheckBoxMenuItemEnglish.setText(bundle.getString("English")); // NOI18N
        jCheckBoxMenuItemEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEnglishActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemEnglish);

        jMenuSettings.add(jMenuLanguage);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEnglishActionPerformed
        this.changeLanguage("en", "US");
        jCheckBoxMenuItemDeutsch.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMenuItemEnglishActionPerformed

    private void jCheckBoxMenuItemDeutschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDeutschActionPerformed
        this.changeLanguage("de", "DE");
        jCheckBoxMenuItemEnglish.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMenuItemDeutschActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDeutsch;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEnglish;
    private javax.swing.JLabel jLabelFairyCyclePF;
    private javax.swing.JLabel jLabelLadiesCyclePF;
    private javax.swing.JLabel jLabelMenCyclePF;
    private javax.swing.JLabel jLabelPeriodNPF;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExportFile;
    private javax.swing.JMenuItem jMenuItemImportFile;
    private javax.swing.JMenu jMenuLanguage;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanelProductionPlanning;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    //util methods
    public void changeLanguage(String lang, String country){
        ResourceBundle i18n = Utils.getResourceBundle(lang, country);
        
        jMenuFile.setText(i18n.getString("File"));
        jMenuSettings.setText(i18n.getString("Settings"));
        jMenuLanguage.setText(i18n.getString("Language"));
        jCheckBoxMenuItemDeutsch.setText(i18n.getString("Deutsch"));
        jCheckBoxMenuItemEnglish.setText(i18n.getString("English"));
        jMenuItemExportFile.setText(i18n.getString("ExportFile"));
        jMenuItemImportFile.setText(i18n.getString("ImportFile"));
    }
}
