/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veloziped.ws1516.main;

import java.io.File;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import veloziped.ws1516.util.IntegerField;
import veloziped.ws1516.util.Utils;

/**
 *
 * @author Mihai Sava
 */
public class MainUI extends javax.swing.JFrame {

    private JTextField IntegerField;
    private Locale locale = Locale.getDefault();

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        SetupInstance.getInstance().readWorkplaceJson();
        SetupInstance.getInstance().readArticleJson();
        initComponents();
        
        //set Language selected
        this.setSelectedLanguage(Locale.getDefault().getLanguage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPan = new javax.swing.JTabbedPane();
        jPanelProductionPlanning = new javax.swing.JPanel();
        jLabelKinderfahrradPF = new javax.swing.JLabel();
        jLabelDamenfahrradPF = new javax.swing.JLabel();
        jLabelMenCyclePF = new javax.swing.JLabel();
        jLabelPeriodNPF = new javax.swing.JLabel();
        jLabelPeriodN1PF = new javax.swing.JLabel();
        jLabelPeriodN2PF = new javax.swing.JLabel();
        jLabelPeriodN3PF = new javax.swing.JLabel();
        jTextField5 = new IntegerField();
        jTextField6 = new IntegerField();
        jTextField7 = new IntegerField();
        jTextField8 = new IntegerField();
        jTextField9 = new IntegerField();
        jTextField10 = new IntegerField();
        jTextField11 = new IntegerField();
        jTextField12 = new IntegerField();
        jTextField13 = new IntegerField();
        jTextField14 = new IntegerField();
        jTextField15 = new IntegerField();
        jTextField16 = new IntegerField();
        jPanelInHouseProduction = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new IntegerField();
        jTextField2 = new IntegerField();
        jTextField3 = new IntegerField();
        jTextField4 = new IntegerField();
        jTextField17 = new IntegerField();
        jTextField18 = new IntegerField();
        jTextField19 = new IntegerField();
        jTextField20 = new IntegerField();
        jTextField21 = new IntegerField();
        jTextField22 = new IntegerField();
        jTextField23 = new IntegerField();
        jTextField24 = new IntegerField();
        jTextField51 = new IntegerField();
        jTextField52 = new IntegerField();
        jTextField53 = new IntegerField();
        jTextField54 = new IntegerField();
        jTextField55 = new IntegerField();
        jTextField56 = new IntegerField();
        jTextField57 = new IntegerField();
        jTextField58 = new IntegerField();
        jTextField59 = new IntegerField();
        jTextField60 = new IntegerField();
        jTextField61 = new IntegerField();
        jTextField62 = new IntegerField();
        jTextField63 = new IntegerField();
        jTextField64 = new IntegerField();
        jTextField65 = new IntegerField();
        jTextField66 = new IntegerField();
        jTextField67 = new IntegerField();
        jTextField68 = new IntegerField();
        jTextField69 = new IntegerField();
        jTextField70 = new IntegerField();
        jTextField71 = new IntegerField();
        jTextField72 = new IntegerField();
        jTextField73 = new IntegerField();
        jTextField74 = new IntegerField();
        jTextField75 = new IntegerField();
        jTextField76 = new IntegerField();
        jTextField77 = new IntegerField();
        jTextField78 = new IntegerField();
        jTextField79 = new IntegerField();
        jTextField80 = new IntegerField();
        jTextField81 = new IntegerField();
        jTextField82 = new IntegerField();
        jTextField83 = new IntegerField();
        jTextField84 = new IntegerField();
        jTextField85 = new IntegerField();
        jTextField86 = new IntegerField();
        jTextField87 = new IntegerField();
        jTextField88 = new IntegerField();
        jTextField89 = new IntegerField();
        jTextField90 = new IntegerField();
        jTextField91 = new IntegerField();
        jTextField92 = new IntegerField();
        jTextField93 = new IntegerField();
        jTextField94 = new IntegerField();
        jTextField95 = new IntegerField();
        jTextField96 = new IntegerField();
        jTextField97 = new IntegerField();
        jTextField98 = new IntegerField();
        jTextField99 = new IntegerField();
        jTextField100 = new IntegerField();
        jTextField101 = new IntegerField();
        jTextField102 = new IntegerField();
        jTextField103 = new IntegerField();
        jTextField104 = new IntegerField();
        jTextField105 = new IntegerField();
        jTextField106 = new IntegerField();
        jTextField107 = new IntegerField();
        jTextField108 = new IntegerField();
        jTextField109 = new IntegerField();
        jTextField110 = new IntegerField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImportFile = new javax.swing.JMenuItem();
        jMenuItemExportFile = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuLanguage = new javax.swing.JMenu();
        jCheckBoxMenuItemBulgarian = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDeutsch = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEnglish = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemFrench = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemRomanien = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("veloziped/ws1516/i18n/i18n"); // NOI18N
        setTitle(bundle.getString("pps")); // NOI18N

        jPanelProductionPlanning.setAutoscrolls(true);

        jLabelKinderfahrradPF.setText(bundle.getString("Kinderfahrrad")); // NOI18N

        jLabelDamenfahrradPF.setText(bundle.getString("Damenfahrrad")); // NOI18N

        jLabelMenCyclePF.setText(bundle.getString("Herrenfahrrad")); // NOI18N

        jLabelPeriodNPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeriodNPF.setText(bundle.getString("PeriondN")); // NOI18N

        jLabelPeriodN1PF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeriodN1PF.setText(bundle.getString("PeriondN1")); // NOI18N

        jLabelPeriodN2PF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeriodN2PF.setText(bundle.getString("PeriondN2")); // NOI18N

        jLabelPeriodN3PF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeriodN3PF.setText(bundle.getString("PeriondN3")); // NOI18N

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelProductionPlanningLayout = new javax.swing.GroupLayout(jPanelProductionPlanning);
        jPanelProductionPlanning.setLayout(jPanelProductionPlanningLayout);
        jPanelProductionPlanningLayout.setHorizontalGroup(
            jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMenCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDamenfahrradPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKinderfahrradPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9)
                    .addComponent(jLabelPeriodNPF, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(jTextField13))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10)
                    .addComponent(jLabelPeriodN1PF, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField14))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11)
                    .addComponent(jLabelPeriodN2PF, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextField7)
                    .addComponent(jTextField15))
                .addGap(18, 18, 18)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPeriodN3PF, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jTextField12)
                    .addComponent(jTextField16))
                .addGap(142, 142, 142))
        );
        jPanelProductionPlanningLayout.setVerticalGroup(
            jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductionPlanningLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeriodNPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPeriodN1PF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPeriodN2PF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPeriodN3PF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKinderfahrradPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDamenfahrradPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelProductionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMenCyclePF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jTabbedPan.addTab(bundle.getString("tabProductionForecast"), jPanelProductionPlanning); // NOI18N

        jPanel1.setMaximumSize(new java.awt.Dimension(16, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(16, 28));
        jPanel1.setSize(new java.awt.Dimension(16, 28));

        jLabel11.setMaximumSize(new java.awt.Dimension(30, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(30, 14));

        jLabel29.setText("jLabel1");
        jLabel29.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel29.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel29.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        jLabel6.setText("jLabel1");

        jLabel7.setText("jLabel1");

        jLabel8.setText("jLabel1");

        jLabel13.setText("jLabel1");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField19.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField22.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField51.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField52.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField53.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField54.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField55.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField56.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField57.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField58.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField59.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField60.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField61.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField62.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField63.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField64.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField65.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField66.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField67.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField68.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField69.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField70.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField71.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField72.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField73.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField74.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField75.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField76.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField77.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField78.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField79.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField80.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField81.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField82.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField83.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField84.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField85.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField86.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField87.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField88.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField89.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField90.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField91.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField92.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField93.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField94.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField95.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField96.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField97.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField98.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField99.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField100.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField101.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField102.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField103.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField104.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField105.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField106.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField107.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField108.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField109.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField110.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel47.setText("jLabel1");
        jLabel47.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel47.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel47.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel48.setText("jLabel1");
        jLabel48.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel48.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel48.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel49.setText("jLabel1");
        jLabel49.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel49.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel49.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel50.setText("jLabel1");
        jLabel50.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel50.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel50.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel51.setText("jLabel1");
        jLabel51.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel51.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel51.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel52.setText("jLabel1");
        jLabel52.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel52.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel52.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel53.setText("jLabel1");
        jLabel53.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel53.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel53.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel54.setText("jLabel1");
        jLabel54.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel54.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel54.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel55.setText("jLabel1");
        jLabel55.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel55.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel55.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel59.setText("jLabel1");
        jLabel59.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel59.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel59.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel60.setText("jLabel1");
        jLabel60.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel60.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel60.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel56.setText("jLabel1");
        jLabel56.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel56.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel56.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel57.setText("jLabel1");
        jLabel57.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel57.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel57.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel58.setText("jLabel1");
        jLabel58.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel58.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel58.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel61.setText("jLabel1");
        jLabel61.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel61.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel61.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel62.setText("jLabel1");
        jLabel62.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel62.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel62.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel63.setText("jLabel1");
        jLabel63.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel63.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel63.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel64.setText("jLabel1");
        jLabel64.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel64.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel64.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel65.setText("jLabel1");
        jLabel65.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel65.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel65.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel66.setText("jLabel1");
        jLabel66.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel66.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel66.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel67.setText("jLabel1");
        jLabel67.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel67.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel67.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel68.setText("jLabel1");
        jLabel68.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel68.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel68.setPreferredSize(new java.awt.Dimension(60, 16));

        jLabel69.setText("jLabel1");
        jLabel69.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel69.setMinimumSize(new java.awt.Dimension(60, 16));
        jLabel69.setPreferredSize(new java.awt.Dimension(60, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField17)
                    .addComponent(jTextField18)
                    .addComponent(jTextField19)
                    .addComponent(jTextField20)
                    .addComponent(jTextField21)
                    .addComponent(jTextField22)
                    .addComponent(jTextField23)
                    .addComponent(jTextField24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField99, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField104, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField106, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField107, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField108, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField109, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField110, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField51)
                    .addComponent(jTextField52)
                    .addComponent(jTextField53)
                    .addComponent(jTextField54, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField55, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField56)
                    .addComponent(jTextField57)
                    .addComponent(jTextField58, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField59)
                    .addComponent(jTextField60)
                    .addComponent(jTextField61, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField63)
                    .addComponent(jTextField64, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField65)
                    .addComponent(jTextField66)
                    .addComponent(jTextField67)
                    .addComponent(jTextField68)
                    .addComponent(jTextField69)
                    .addComponent(jTextField70)
                    .addComponent(jTextField71)
                    .addComponent(jTextField72)
                    .addComponent(jTextField73)
                    .addComponent(jTextField74))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField75)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField76, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField77)
                    .addComponent(jTextField78)
                    .addComponent(jTextField79)
                    .addComponent(jTextField80)
                    .addComponent(jTextField81)
                    .addComponent(jTextField82)
                    .addComponent(jTextField83)
                    .addComponent(jTextField84)
                    .addComponent(jTextField85)
                    .addComponent(jTextField86))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField87)
                    .addComponent(jTextField88)
                    .addComponent(jTextField89)
                    .addComponent(jTextField90)
                    .addComponent(jTextField91, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField92)
                    .addComponent(jTextField93)
                    .addComponent(jTextField94)
                    .addComponent(jTextField95)
                    .addComponent(jTextField96, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField97)
                    .addComponent(jTextField98))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(46, 46, 46)))
                                                                                        .addGap(34, 34, 34))
                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField99, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jTextField101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGap(18, 18, 18)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextField90, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                            .addComponent(jTextField102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jTextField103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextField91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(34, 34, 34))
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField93, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jTextField105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField95, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField97, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanelInHouseProductionLayout = new javax.swing.GroupLayout(jPanelInHouseProduction);
        jPanelInHouseProduction.setLayout(jPanelInHouseProductionLayout);
        jPanelInHouseProductionLayout.setHorizontalGroup(
            jPanelInHouseProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInHouseProductionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        jPanelInHouseProductionLayout.setVerticalGroup(
            jPanelInHouseProductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInHouseProductionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPan.addTab(bundle.getString("InHauseProduction"), jPanelInHouseProduction); // NOI18N

        jMenuFile.setText(bundle.getString("File")); // NOI18N

        jMenuItemImportFile.setText(bundle.getString("ImportFile")); // NOI18N
        jMenuItemImportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportFileActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemImportFile);

        jMenuItemExportFile.setText(bundle.getString("ExportFile")); // NOI18N
        jMenuFile.add(jMenuItemExportFile);

        jMenuBar1.add(jMenuFile);

        jMenuSettings.setText(bundle.getString("Settings")); // NOI18N

        jMenuLanguage.setText(bundle.getString("Language")); // NOI18N

        jCheckBoxMenuItemBulgarian.setText(bundle.getString("Bulgarian")); // NOI18N
        jCheckBoxMenuItemBulgarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemBulgarianActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemBulgarian);

        jCheckBoxMenuItemDeutsch.setText(bundle.getString("Deutsch")); // NOI18N
        jCheckBoxMenuItemDeutsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDeutschActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemDeutsch);

        jCheckBoxMenuItemEnglish.setText(bundle.getString("English")); // NOI18N
        jCheckBoxMenuItemEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEnglishActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemEnglish);

        jCheckBoxMenuItemFrench.setText(bundle.getString("French")); // NOI18N
        jCheckBoxMenuItemFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemFrenchActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemFrench);

        jCheckBoxMenuItemRomanien.setText(bundle.getString("Romanien")); // NOI18N
        jCheckBoxMenuItemRomanien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemRomanienActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jCheckBoxMenuItemRomanien);

        jMenuSettings.add(jMenuLanguage);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEnglishActionPerformed
        locale = new Locale("en","US");
        this.changeLanguage(locale.getLanguage(), locale.getCountry());
        jCheckBoxMenuItemDeutsch.setSelected(false);
        jCheckBoxMenuItemBulgarian.setSelected(false);
        jCheckBoxMenuItemFrench.setSelected(false);
        jCheckBoxMenuItemRomanien.setSelected(false);      
    }//GEN-LAST:event_jCheckBoxMenuItemEnglishActionPerformed

    private void jCheckBoxMenuItemDeutschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDeutschActionPerformed
        locale = new Locale("de","DE");
        this.changeLanguage(locale.getLanguage(), locale.getCountry());
        jCheckBoxMenuItemEnglish.setSelected(false);
        jCheckBoxMenuItemBulgarian.setSelected(false);
        jCheckBoxMenuItemFrench.setSelected(false);
        jCheckBoxMenuItemRomanien.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMenuItemDeutschActionPerformed

    private void jCheckBoxMenuItemBulgarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemBulgarianActionPerformed
        locale = new Locale("bg","BG");
        this.changeLanguage(locale.getLanguage(), locale.getCountry());
        jCheckBoxMenuItemEnglish.setSelected(false);
        jCheckBoxMenuItemDeutsch.setSelected(false);
        jCheckBoxMenuItemFrench.setSelected(false);
        jCheckBoxMenuItemRomanien.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMenuItemBulgarianActionPerformed

    private void jCheckBoxMenuItemFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemFrenchActionPerformed
        locale = new Locale("fr","FR");
        this.changeLanguage(locale.getLanguage(), locale.getCountry());
        jCheckBoxMenuItemEnglish.setSelected(false);
        jCheckBoxMenuItemDeutsch.setSelected(false);
        jCheckBoxMenuItemBulgarian.setSelected(false);
        jCheckBoxMenuItemRomanien.setSelected(false); 
    }//GEN-LAST:event_jCheckBoxMenuItemFrenchActionPerformed

    private void jCheckBoxMenuItemRomanienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemRomanienActionPerformed
        locale = new Locale("ro","RO");
        this.changeLanguage(locale.getLanguage(), locale.getCountry());
        jCheckBoxMenuItemEnglish.setSelected(false);
        jCheckBoxMenuItemDeutsch.setSelected(false);
        jCheckBoxMenuItemFrench.setSelected(false);
        jCheckBoxMenuItemBulgarian.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMenuItemRomanienActionPerformed

    private void jMenuItemImportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportFileActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
       File file = chooser.getSelectedFile();
       if (file.getAbsolutePath().endsWith(".xml")){
           
       }else{
           ResourceBundle i18n = Utils.getResourceBundle(locale.getLanguage(), locale.getCountry());
           JOptionPane.showMessageDialog(this, i18n.getString("OnlyXML"), null, JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jMenuItemImportFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemBulgarian;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDeutsch;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEnglish;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemFrench;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemRomanien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDamenfahrradPF;
    private javax.swing.JLabel jLabelKinderfahrradPF;
    private javax.swing.JLabel jLabelMenCyclePF;
    private javax.swing.JLabel jLabelPeriodN1PF;
    private javax.swing.JLabel jLabelPeriodN2PF;
    private javax.swing.JLabel jLabelPeriodN3PF;
    private javax.swing.JLabel jLabelPeriodNPF;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExportFile;
    private javax.swing.JMenuItem jMenuItemImportFile;
    private javax.swing.JMenu jMenuLanguage;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInHouseProduction;
    private javax.swing.JPanel jPanelProductionPlanning;
    private javax.swing.JTabbedPane jTabbedPan;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField100;
    private javax.swing.JTextField jTextField101;
    private javax.swing.JTextField jTextField102;
    private javax.swing.JTextField jTextField103;
    private javax.swing.JTextField jTextField104;
    private javax.swing.JTextField jTextField105;
    private javax.swing.JTextField jTextField106;
    private javax.swing.JTextField jTextField107;
    private javax.swing.JTextField jTextField108;
    private javax.swing.JTextField jTextField109;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField110;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTextField jTextField95;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    // End of variables declaration//GEN-END:variables

    //util methods
    public void changeLanguage(String lang, String country){
        ResourceBundle i18n = Utils.getResourceBundle(lang, country);
        
        jMenuFile.setText(i18n.getString("File"));
        jMenuSettings.setText(i18n.getString("Settings"));
        jMenuLanguage.setText(i18n.getString("Language"));
        jCheckBoxMenuItemDeutsch.setText(i18n.getString("Deutsch"));
        jCheckBoxMenuItemEnglish.setText(i18n.getString("English"));
        jMenuItemExportFile.setText(i18n.getString("ExportFile"));
        jMenuItemImportFile.setText(i18n.getString("ImportFile"));
    }
    
    public void setSelectedLanguage(String language){
        switch(language){
            case "en":
                jCheckBoxMenuItemEnglish.setSelected(true);
                break;
            case "de":
                jCheckBoxMenuItemDeutsch.setSelected(true);
                break;
            case "ro":
                jCheckBoxMenuItemRomanien.setSelected(true);
                break;
            case "bg":
                jCheckBoxMenuItemBulgarian.setSelected(true);
                break;
             case "fr":
                jCheckBoxMenuItemFrench.setSelected(true);
                break;
            default:
                jCheckBoxMenuItemEnglish.setSelected(true);
        }
    }
}
